version: "3"
services:
  historydb:
   container_name: historydb
   image : mongo
   ports :
   - "27018:27017"
   volumes :
     - db-volume:/data
     - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD : root
     MONGO_INITDB_DATABASE: history
  history:
    container_name: mediscreen-history
    build: .
    image: history:lastest
    ports:
        - "8082:8082"
    depends_on:
      - historydb
    environment:
      MONGO_HOST: historydb
      MONGO_PORT: 27017

volumes:
  db-volume:

