version: "3"
services:
  patientdb:
    container_name: patientdb
    image: mysql:8.0.29
    command:
      --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: patient
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - db-volume:/var/lib/mysql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2.sql
  patient:
    container_name: mediscreen-patient
    build: .
    image: patient:lastest
    ports:
      - "8081:8081"
    depends_on:
      - patientdb
    environment:
      MYSQL_HOST: patientdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306

volumes:
  db-volume: